const GalleryParameters = Object.freeze({
  HIDDEN: 'hidden',
  DISABLE_SCROLLING: 'modal-open',
  DISABLE_SCROLLING_ELEMENT: 'body',
  GALLERY_CONTAINER: '.pictures',
  GALLERY_TEMPLATE: '#picture',
  GALLERY_TEMPLATE_LINK: '.picture',
  GALLERY_TEMPLATE_IMAGE: '.picture__img',
  GALLERY_TEMPLATE_COMMENTS: '.picture__comments',
  GALLERY_TEMPLATE_LIKES: '.picture__likes',
  BIG_PHOTO_CONTAINER: '.big-picture',
  BIG_PHOTO_IMG: '.big-picture__img',
  BIG_PHOTO_DESCRIPTION: '.social__caption',
  BIG_PHOTO_LIKES: '.likes-count',
  BIG_PHOTO_CLOSE: '.big-picture__cancel',
  COMMENTS_LOADER_BUTTON: '.comments-loader',
  SOCIAL_CONTAINER: '.social',
  SOCIAL_COMMENTS: '.social__comments',
  AVATAR: 'social__picture',
  AVATAR_WIDTH: 35,
  AVATAR_HEIGHT: 35,
  SHOWN_COMMENTS_LENGTH: 5,
  COUNT_SHOWN_COMMENTS: '.social__comment-shown-count',
  COUNT_TOTAL_COMMENTS: '.social__comment-total-count',
  COMMENT_TAG: 'li',
  COMMENT_TEXT_TAG: 'p',
  COMMENT_ITEM: 'social__comment',
  COMMENT_TEXT: 'social__text'
});

const FormParameters = Object.freeze({
  BASE_URL: 'https://32.javascript.htmlacademy.pro/kekstagram',
  GET_DATA: '/data/',
  SEND_DATA: '/',
  UPLOAD_BLOCK: '.img-upload',
  UPLOAD_FORM: '.img-upload__form',
  UPLOAD_IMAGE_INPUT: '.img-upload__input',
  UPLOAD_IMAGE_PREVIEW: '.img-upload__preview',
  HASHTAGS_INPUT: '.text__hashtags',
  COMMENTS_TEXT: '.text__description',
  EDITING_BLOCK: '.img-upload__overlay',
  BUTTON_SMALLER: '.scale__control--smaller',
  BUTTON_BIGGER: '.scale__control--bigger',
  SCALE_INPUT: '.scale__control--value',
  EFFECT_LEVEL: '.img-upload__effect-level',
  SLIDER_ELEMENT: '.effect-level__slider',
  VALUE_ELEMENT: '.effect-level__value',
  EFFECT_NONE: '#effect-none',
  EFFECT_CHROME: '#effect-chrome',
  EFFECT_SEPIA: '#effect-sepia',
  EFFECT_MARVIN: '#effect-marvin',
  EFFECT_PHOBOS: '#effect-phobos',
  EFFECT_HEAT: '#effect-heat',
  FORM_CLOSE: '.img-upload__cancel',
  ERROR_TEMPLATE: '#error',
  ERROR_BUTTON: '.error__button',
  ERROR_INNER: '.error__inner',
  SUCCESS_TEMPLATE: '#success',
  SUCCESS_BUTTON: '.success__button',
  SUCCESS_INNER: '.success__inner',
  ERROR_DATA_TEMPLATE: '#data-error',
  UPLOAD_MESSAGE: '.upload-message',
  UPLOAD_SUBMIT_BUTTON: '.img-upload__submit'
});

const ErrorMessages = Object.freeze({
  ERROR_MESSAGE_1: 'Хештегов должно быть не более пяти.<br>',
  ERROR_MESSAGE_2: 'Не должно быть одинаковых хештегов (хештеги нечувствительны к регистру).<br>',
  ERROR_MESSAGE_3: 'Хэштеги должны начинаться с символа #.<br>',
  ERROR_MESSAGE_4: 'Хештег не должен состоять из одной #.<br>',
  ERROR_MESSAGE_5: 'Максимальная длина хештега - 20 символов, включая #.<br>',
  ERROR_MESSAGE_6: 'Хештег после # должен содержать только буквы и числа<br>'
});

export { GalleryParameters, FormParameters, ErrorMessages };
